---
all:
  hosts:
    ansible-01-deb:
      ansible_host: 49.12.46.24
    ansible-01-rh:
      ansible_host: 138.201.172.211    
  vars:
    ansible_user: root
    ansible_port: 10022
    ansible_ssh_private_key_file: ~/.ssh/docean
